language: node_js
node_js:
  - "stable"
cache:
  directories:
    - public
    - .cahce
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  #The branch where it should deploy
  target_branch: gh-pages
  on:
    branch: main